# Generated by Django 3.2.3 on 2021-10-03 06:55

import apps.movies.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name of Movie/Serial')),
                ('was_shot_by', models.CharField(max_length=100, verbose_name='Film was shot by whom or which studio')),
                ('released_in', models.DateField(verbose_name='Film was released in')),
                ('duration', models.CharField(max_length=100, verbose_name='Duration of film')),
                ('actors', models.CharField(max_length=150, verbose_name='Actors who starred in the film')),
                ('description', models.TextField(verbose_name='Detailed information about film')),
                ('video', models.FileField(upload_to=apps.movies.models.get_img_upload_path, verbose_name='Video content of film')),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('serial', 'Serial')], max_length=50, verbose_name='Type of film')),
                ('uploaded_to_platform_in', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(related_name='films', to='movies.Genre')),
                ('uploaded_to_platform_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Satisfied'), (4, 'Excellent'), (5, 'Masterpiece')])),
                ('rating_of_film', models.IntegerField(default=0)),
                ('opinion', models.TextField(blank=True, null=True)),
                ('num_rated_users', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie')),
                ('rated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
