# Generated by Django 3.2.3 on 2021-10-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_of_film',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
    ]
