# Generated by Django 3.2.3 on 2021-10-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_rating_rating_of_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_of_film',
            field=models.FloatField(default=0.0, max_length=1),
        ),
    ]
