# Generated by Django 3.2.3 on 2021-10-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_rating_rating_of_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='num_rated_users',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_of_film',
        ),
        migrations.AddField(
            model_name='movie',
            name='num_rated_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating_of_film',
            field=models.FloatField(default=0.0, max_length=1),
        ),
    ]
